export default [
    {
        id: 'dp6-90',
        name: 'Cubone',
        nationalPokedexNumber: 104,
        imageUrl: 'https://images.pokemontcg.io/dp6/90.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/dp6/90_hires.png',
        types: ['Fighting'],
        supertype: 'Pokémon',
        subtype: 'Basic',
        hp: '60',
        retreatCost: ['Colorless'],
        convertedRetreatCost: 1,
        number: '90',
        artist: 'Kagemaru Himeno',
        rarity: 'Common',
        series: 'Diamond & Pearl',
        set: 'Legends Awakened',
        setCode: 'dp6',
        attacks: [
            {
                cost: ['Colorless'],
                name: 'Headbutt',
                text: '',
                damage: '10',
                convertedEnergyCost: 1,
            },
            {
                cost: ['Fighting', 'Colorless'],
                name: 'Bonemerang',
                text:
                    'Flip 2 coins. This attack does 20 damage times the number of heads.',
                damage: '20×',
                convertedEnergyCost: 2,
            },
        ],
        resistances: [{ type: 'Lightning', value: '-20' }],
        weaknesses: [{ type: 'Water', value: '+10' }],
    },
    {
        id: 'ex14-85',
        name: 'Windstorm',
        imageUrl: 'https://images.pokemontcg.io/ex14/85.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/ex14/85_hires.png',
        supertype: 'Trainer',
        subtype: 'Item',
        hp: 'None',
        number: '85',
        artist: 'Ryo Ueda',
        rarity: 'Uncommon',
        series: 'EX',
        set: 'Crystal Guardians',
        setCode: 'ex14',
        text: [
            "Choose up to 2 in any combination of Pokémon Tool cards and Stadium cards in play (both yours and your opponent's) and discard them.",
        ],
    },
    {
        id: 'pop9-17',
        name: 'Turtwig',
        nationalPokedexNumber: 387,
        imageUrl: 'https://images.pokemontcg.io/pop9/17.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/pop9/17_hires.png',
        types: ['Grass'],
        supertype: 'Pokémon',
        subtype: 'Basic',
        hp: '60',
        retreatCost: ['Colorless', 'Colorless'],
        convertedRetreatCost: 2,
        number: '17',
        artist: 'Midori Harada',
        rarity: 'Common',
        series: 'POP',
        set: 'POP Series 9',
        setCode: 'pop9',
        attacks: [
            {
                cost: ['Grass'],
                name: 'Absorb',
                text: 'Remove 1 damage counter from Turtwig.',
                damage: '10',
                convertedEnergyCost: 1,
            },
            {
                cost: ['Grass', 'Colorless', 'Colorless'],
                name: 'Parboil',
                text:
                    'If you have Chimchar in play, this attack does 40 damage plus 20 more damage and the Defending Pokémon is now Burned.',
                damage: '40+',
                convertedEnergyCost: 3,
            },
        ],
        resistances: [{ type: 'Water', value: '-20' }],
        weaknesses: [{ type: 'Fire', value: '×2' }],
    },
    {
        id: 'xy7-4',
        name: 'Bellossom',
        nationalPokedexNumber: 182,
        imageUrl: 'https://images.pokemontcg.io/xy7/4.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/xy7/4_hires.png',
        types: ['Grass'],
        supertype: 'Pokémon',
        subtype: 'Stage 2',
        evolvesFrom: 'Gloom',
        hp: '120',
        retreatCost: ['Colorless'],
        convertedRetreatCost: 1,
        number: '4',
        artist: 'Mizue',
        rarity: 'Uncommon',
        series: 'XY',
        set: 'Ancient Origins',
        setCode: 'xy7',
        attacks: [
            {
                cost: ['Grass'],
                name: 'Windmill',
                text: 'Switch this Pokémon with 1 of your Benched Pokémon.',
                damage: '20',
                convertedEnergyCost: 1,
            },
            {
                cost: ['Grass', 'Colorless'],
                name: 'Flower Tornado',
                text:
                    'Move as many Grass Energy attached to your Pokémon to your other Pokémon in any way you like.',
                damage: '60',
                convertedEnergyCost: 2,
            },
        ],
        weaknesses: [{ type: 'Fire', value: '×2' }],
    },
    {
        id: 'ex8-100',
        name: 'Hariyama ex',
        nationalPokedexNumber: 297,
        imageUrl: 'https://images.pokemontcg.io/ex8/100.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/ex8/100_hires.png',
        types: ['Fighting'],
        supertype: 'Pokémon',
        subtype: 'EX',
        evolvesFrom: 'Makuhita',
        ability: {
            name: 'Commanding Aura',
            text:
                "As long as Hariyama ex is your Active Pokémon, your opponent can't play any Stadium cards from his or her hand.",
            type: 'Poké-Body',
        },
        hp: '110',
        retreatCost: ['Colorless', 'Colorless'],
        convertedRetreatCost: 2,
        number: '100',
        artist: 'Ryo Ueda',
        rarity: 'Rare Holo EX',
        series: 'EX',
        set: 'Deoxys',
        setCode: 'ex8',
        text: [
            'When Pokémon-ex has been Knocked Out, your opponent takes 2 Prize cards.',
        ],
        attacks: [
            {
                cost: ['Fighting', 'Colorless'],
                name: 'Knock Off',
                text:
                    "Choose 1 card from your opponent's hand without looking and discard it.",
                damage: '40',
                convertedEnergyCost: 2,
            },
            {
                cost: ['Fighting', 'Fighting', 'Colorless'],
                name: 'Pivot Throw',
                text:
                    "During your opponent's next turn, any damage done to Hariyama ex by attacks is increased by 10 (before applying Weakness and Resistance).",
                damage: '80',
                convertedEnergyCost: 3,
            },
        ],
        weaknesses: [{ type: 'Psychic', value: '×2' }],
    },
    {
        id: 'xyp-XY05',
        name: 'Xerneas',
        nationalPokedexNumber: 716,
        imageUrl: 'https://images.pokemontcg.io/xyp/XY05.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/xyp/XY05_hires.png',
        types: ['Fairy'],
        supertype: 'Pokémon',
        subtype: 'Basic',
        hp: '130',
        retreatCost: ['Colorless', 'Colorless'],
        convertedRetreatCost: 2,
        number: 'XY05',
        artist: '5ban Graphics',
        rarity: 'Rare',
        series: 'XY',
        set: 'XY Black Star Promos',
        setCode: 'xyp',
        attacks: [
            {
                cost: ['Fairy'],
                name: 'Geomancy',
                text:
                    'Choose 2 of your Benched Pokémon. For each of those Pokémon, search your deck for a Fairy Energy card and attach it to that Pokémon. Shuffle your deck afterward.',
                damage: '',
                convertedEnergyCost: 1,
            },
            {
                cost: ['Fairy', 'Fairy', 'Colorless'],
                name: 'Rainbow Spear',
                text: 'Discard an Energy attached to this Pokémon.',
                damage: '100',
                convertedEnergyCost: 3,
            },
        ],
        resistances: [{ type: 'Darkness', value: '-20' }],
        weaknesses: [{ type: 'Metal', value: '×2' }],
    },
    {
        id: 'ex16-1',
        name: 'Aggron',
        nationalPokedexNumber: 306,
        imageUrl: 'https://images.pokemontcg.io/ex16/1.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/ex16/1_hires.png',
        types: ['Metal'],
        supertype: 'Pokémon',
        subtype: 'Stage 2',
        evolvesFrom: 'Lairon',
        ability: {
            name: 'Terraforming',
            text:
                "Once during your turn (before your attack), you may look at the top 5 cards from your deck and put them back on top of your deck in any order. This power can't be used if Aggron is affected by a Special Condition.",
            type: 'Poké-Power',
        },
        hp: '110',
        retreatCost: ['Colorless', 'Colorless', 'Colorless', 'Colorless'],
        convertedRetreatCost: 4,
        number: '1',
        artist: 'Ken Sugimori',
        rarity: 'Rare Holo',
        series: 'EX',
        set: 'Power Keepers',
        setCode: 'ex16',
        attacks: [
            {
                cost: ['Colorless', 'Colorless', 'Colorless'],
                name: 'Metal Claw',
                text: '',
                damage: '50',
                convertedEnergyCost: 3,
            },
            {
                cost: ['Metal', 'Metal', 'Colorless', 'Colorless'],
                name: 'Mix-Up',
                text: 'Your opponent discards the top card of his or her deck.',
                damage: '70',
                convertedEnergyCost: 4,
            },
        ],
        resistances: [{ type: 'Grass', value: '-30' }],
        weaknesses: [{ type: 'Fire', value: '×2' }],
    },
    {
        id: 'xyp-XY11',
        name: 'Skiddo',
        nationalPokedexNumber: 672,
        imageUrl: 'https://images.pokemontcg.io/xyp/XY11.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/xyp/XY11_hires.png',
        types: ['Grass'],
        supertype: 'Pokémon',
        subtype: 'Basic',
        hp: '70',
        retreatCost: ['Colorless', 'Colorless'],
        convertedRetreatCost: 2,
        number: 'XY11',
        artist: '5ban Graphics',
        rarity: '',
        series: 'XY',
        set: 'XY Black Star Promos',
        setCode: 'xyp',
        attacks: [
            {
                cost: ['Grass', 'Grass'],
                name: 'Take Down',
                text: 'This Pokémon does 10 damage to itself.',
                damage: '30',
                convertedEnergyCost: 2,
            },
        ],
        weaknesses: [{ type: 'Fire', value: '×2' }],
    },
    {
        id: 'dp6-107',
        name: 'Misdreavus',
        nationalPokedexNumber: 200,
        imageUrl: 'https://images.pokemontcg.io/dp6/107.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/dp6/107_hires.png',
        types: ['Psychic'],
        supertype: 'Pokémon',
        subtype: 'Basic',
        hp: '60',
        retreatCost: ['Colorless'],
        convertedRetreatCost: 1,
        number: '107',
        artist: 'Sumiyoshi Kizuki',
        rarity: 'Common',
        series: 'Diamond & Pearl',
        set: 'Legends Awakened',
        setCode: 'dp6',
        attacks: [
            {
                cost: ['Free'],
                name: 'Show Off',
                text:
                    'Search your deck for a basic Energy card, show it to your opponent, and put it into your hand. Shuffle your deck afterward.',
                damage: '',
                convertedEnergyCost: 0,
            },
            {
                cost: ['Psychic'],
                name: 'Payback',
                text:
                    'If your opponent has only 1 Prize card left, this attack does 10 damage plus 20 more damage.',
                damage: '10+',
                convertedEnergyCost: 1,
            },
        ],
        resistances: [{ type: 'Colorless', value: '-20' }],
        weaknesses: [{ type: 'Darkness', value: '+10' }],
    },
    {
        id: 'xy0-14',
        name: 'Greninja',
        nationalPokedexNumber: 658,
        imageUrl: 'https://images.pokemontcg.io/xy0/14.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/xy0/14_hires.png',
        types: ['Water'],
        supertype: 'Pokémon',
        subtype: 'Stage 2',
        evolvesFrom: 'Frogadier',
        hp: '140',
        retreatCost: ['Colorless'],
        convertedRetreatCost: 1,
        number: '14',
        artist: '5ban Graphics',
        rarity: '',
        series: 'XY',
        set: 'Kalos Starter Set',
        setCode: 'xy0',
        attacks: [
            {
                cost: ['Water'],
                name: 'Mat Block',
                text:
                    "Flip a coin. If heads, discard an Energy attached to your opponent's Active Pokémon.",
                damage: '40',
                convertedEnergyCost: 1,
            },
            {
                cost: ['Water', 'Water', 'Colorless'],
                name: 'Aqua Edge',
                text: '',
                damage: '80',
                convertedEnergyCost: 3,
            },
        ],
        weaknesses: [{ type: 'Grass', value: '×2' }],
    },
    {
        id: 'xy0-15',
        name: 'Clauncher',
        nationalPokedexNumber: 692,
        imageUrl: 'https://images.pokemontcg.io/xy0/15.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/xy0/15_hires.png',
        types: ['Water'],
        supertype: 'Pokémon',
        subtype: 'Basic',
        hp: '70',
        retreatCost: ['Colorless'],
        convertedRetreatCost: 1,
        number: '15',
        artist: '5ban Graphics',
        rarity: '',
        series: 'XY',
        set: 'Kalos Starter Set',
        setCode: 'xy0',
        attacks: [
            {
                cost: ['Water', 'Colorless'],
                name: 'Water Gun',
                text: '',
                damage: '20',
                convertedEnergyCost: 2,
            },
        ],
        weaknesses: [{ type: 'Grass', value: '×2' }],
    },
    {
        id: 'ex16-16',
        name: 'Magneton',
        nationalPokedexNumber: 82,
        imageUrl: 'https://images.pokemontcg.io/ex16/16.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/ex16/16_hires.png',
        types: ['Lightning'],
        supertype: 'Pokémon',
        subtype: 'Stage 1',
        evolvesFrom: 'Magnemite',
        ability: {
            name: 'Magnetic Field',
            text:
                "Once during your turn (before your attack), if you have basic Energy cards in your discard pile, you may discard any 1 card from your hand. Then search for up to 2 basic Energy cards from your discard pile, show them to your opponent, and put them into your hand. You can't return the card you first discarded to your hand in this way. This power can't be used if Magneton is affected by a Special Condition.",
            type: 'Poké-Power',
        },
        hp: '70',
        retreatCost: ['Colorless'],
        convertedRetreatCost: 1,
        number: '16',
        artist: 'Masakazu Fukuda',
        rarity: 'Rare',
        series: 'EX',
        set: 'Power Keepers',
        setCode: 'ex16',
        attacks: [
            {
                cost: ['Lightning', 'Colorless'],
                name: 'Magnetic Force',
                text:
                    'Does 10 damage times the amount of Energy attached to all of your Pokémon (including Magneton).',
                damage: '10×',
                convertedEnergyCost: 2,
            },
        ],
        resistances: [{ type: 'Metal', value: '-30' }],
        weaknesses: [{ type: 'Fighting', value: '×2' }],
    },
    {
        id: 'xy11-41',
        name: 'Joltik',
        nationalPokedexNumber: 595,
        imageUrl: 'https://images.pokemontcg.io/xy11/41.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/xy11/41_hires.png',
        types: ['Lightning'],
        supertype: 'Pokémon',
        subtype: 'Basic',
        hp: '30',
        number: '41',
        artist: 'Ayaka Yoshida',
        rarity: 'Common',
        series: 'XY',
        set: 'Steam Siege',
        setCode: 'xy11',
        attacks: [
            {
                cost: ['Lightning'],
                name: 'Attach',
                text: '',
                damage: '10',
                convertedEnergyCost: 1,
            },
        ],
        resistances: [{ type: 'Metal', value: '-20' }],
        weaknesses: [{ type: 'Fighting', value: '×2' }],
    },
    {
        id: 'xy0-18',
        name: 'Inkay',
        nationalPokedexNumber: 686,
        imageUrl: 'https://images.pokemontcg.io/xy0/18.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/xy0/18_hires.png',
        types: ['Darkness'],
        supertype: 'Pokémon',
        subtype: 'Basic',
        hp: '60',
        retreatCost: ['Colorless'],
        convertedRetreatCost: 1,
        number: '18',
        artist: '5ban Graphics',
        rarity: '',
        series: 'XY',
        set: 'Kalos Starter Set',
        setCode: 'xy0',
        attacks: [
            {
                cost: ['Darkness'],
                name: 'Peck',
                text: '',
                damage: '10',
                convertedEnergyCost: 1,
            },
        ],
        resistances: [{ type: 'Psychic', value: '-20' }],
        weaknesses: [{ type: 'Fighting', value: '×2' }],
    },
    {
        id: 'xy0-17',
        name: 'Mightyena',
        nationalPokedexNumber: 262,
        imageUrl: 'https://images.pokemontcg.io/xy0/17.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/xy0/17_hires.png',
        types: ['Darkness'],
        supertype: 'Pokémon',
        subtype: 'Stage 1',
        evolvesFrom: 'Poochyena',
        hp: '90',
        retreatCost: ['Colorless'],
        convertedRetreatCost: 1,
        number: '17',
        artist: 'Mitsuhiro Arita',
        rarity: '',
        series: 'XY',
        set: 'Kalos Starter Set',
        setCode: 'xy0',
        attacks: [
            {
                cost: ['Darkness', 'Colorless'],
                name: 'Hard Bite',
                text: 'Flip a coin. If heads, this attack does 20 more damage.',
                damage: '40+',
                convertedEnergyCost: 2,
            },
        ],
        resistances: [{ type: 'Psychic', value: '-20' }],
        weaknesses: [{ type: 'Fighting', value: '×2' }],
    },
    {
        id: 'xy0-19',
        name: 'Pawniard',
        nationalPokedexNumber: 624,
        imageUrl: 'https://images.pokemontcg.io/xy0/19.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/xy0/19_hires.png',
        types: ['Metal'],
        supertype: 'Pokémon',
        subtype: 'Basic',
        hp: '60',
        retreatCost: ['Colorless'],
        convertedRetreatCost: 1,
        number: '19',
        artist: 'Kouki Saitou',
        rarity: '',
        series: 'XY',
        set: 'Kalos Starter Set',
        setCode: 'xy0',
        attacks: [
            {
                cost: ['Metal'],
                name: 'Pierce',
                text: '',
                damage: '10',
                convertedEnergyCost: 1,
            },
            {
                cost: ['Colorless', 'Colorless'],
                name: 'Cut',
                text: '',
                damage: '20',
                convertedEnergyCost: 2,
            },
        ],
        resistances: [{ type: 'Psychic', value: '-20' }],
        weaknesses: [{ type: 'Fire', value: '×2' }],
    },
    {
        id: 'dp6-113',
        name: 'Pineco',
        nationalPokedexNumber: 204,
        imageUrl: 'https://images.pokemontcg.io/dp6/113.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/dp6/113_hires.png',
        types: ['Grass'],
        supertype: 'Pokémon',
        subtype: 'Basic',
        hp: '50',
        retreatCost: ['Colorless'],
        convertedRetreatCost: 1,
        number: '113',
        artist: 'Masakazu Fukuda',
        rarity: 'Common',
        series: 'Diamond & Pearl',
        set: 'Legends Awakened',
        setCode: 'dp6',
        attacks: [
            {
                cost: ['Colorless'],
                name: 'Tackle',
                text: '',
                damage: '10',
                convertedEnergyCost: 1,
            },
            {
                cost: ['Grass', 'Colorless'],
                name: 'Selfdestruct',
                text:
                    "This attack does 10 damage to each Benched Pokémon (both yours and your opponent's). (Don't apply Weakness and Resistance for Benched Pokémon.) Pineco does 50 damage to itself.",
                damage: '40',
                convertedEnergyCost: 2,
            },
        ],
        weaknesses: [{ type: 'Fire', value: '+10' }],
    },
    {
        id: 'ex16-30',
        name: 'Glalie',
        nationalPokedexNumber: 362,
        imageUrl: 'https://images.pokemontcg.io/ex16/30.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/ex16/30_hires.png',
        types: ['Water'],
        supertype: 'Pokémon',
        subtype: 'Stage 1',
        evolvesFrom: 'Snorunt',
        ability: {
            name: 'Synergy Effect',
            text:
                "If Glacia's Stadium is in play, any damage done to Glalie by attacks from your opponent's Pokémon is reduced by 30 (after applying Weakness and Resistance).",
            type: 'Poké-Body',
        },
        hp: '80',
        retreatCost: ['Colorless'],
        convertedRetreatCost: 1,
        number: '30',
        artist: 'Ken Sugimori',
        rarity: 'Uncommon',
        series: 'EX',
        set: 'Power Keepers',
        setCode: 'ex16',
        attacks: [
            {
                cost: ['Water', 'Colorless'],
                name: 'Powder Snow',
                text: 'The Defending Pokémon is now Asleep.',
                damage: '20',
                convertedEnergyCost: 2,
            },
            {
                cost: ['Water', 'Colorless', 'Colorless'],
                name: 'Double-edge',
                text: 'Glalie does 10 damage to itself.',
                damage: '60',
                convertedEnergyCost: 3,
            },
        ],
        weaknesses: [{ type: 'Metal', value: '×2' }],
    },
    {
        id: 'base4-112',
        name: 'Maintenance',
        imageUrl: 'https://images.pokemontcg.io/base4/112.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/base4/112_hires.png',
        supertype: 'Trainer',
        subtype: '',
        number: '112',
        artist: 'Keiji Kinebuchi',
        rarity: 'Uncommon',
        series: 'Base',
        set: 'Base Set 2',
        setCode: 'base4',
        text: [
            'Shuffle 2 of the other cards from your hand into your deck in order to draw a card.',
        ],
    },
    {
        id: 'xy11-25',
        name: 'Volcanion',
        nationalPokedexNumber: 721,
        imageUrl: 'https://images.pokemontcg.io/xy11/25.png',
        imageUrlHiRes: 'https://images.pokemontcg.io/xy11/25_hires.png',
        types: ['Fire'],
        supertype: 'Pokémon',
        subtype: 'Basic',
        hp: '130',
        retreatCost: ['Colorless', 'Colorless'],
        convertedRetreatCost: 2,
        number: '25',
        artist: '5ban Graphics',
        rarity: 'Rare',
        series: 'XY',
        set: 'Steam Siege',
        setCode: 'xy11',
        attacks: [
            {
                cost: ['Fire'],
                name: 'Power Heater',
                text:
                    'Choose 2 of your Benched Pokémon. Attach a Fire Energy card from your discard pile to each of those Pokémon.',
                damage: '20',
                convertedEnergyCost: 1,
            },
            {
                cost: ['Fire', 'Fire', 'Fire'],
                name: 'Steam Artillery',
                text: '',
                damage: '100',
                convertedEnergyCost: 3,
            },
        ],
        weaknesses: [{ type: 'Water', value: '×2' }],
    },
];
